### ISSUE TITLE
What can be the use cases of this package?

### ISSUE THREAD

**Issue by shubhamdeol** [cawfree/react-native-quiet#2]

**Comment by cawfree** [comment]
Hey there!

The ability to broadcast to a listeners in a close proximity can be useful for a number of different possibilities. For example, sound could be used as the medium for a contactless card payment, a messaging app, or push-notification driven advertising. The only limit is your imagination!

Check out the full discussion over on [Reddit](https://www.reddit.com/r/reactnative/comments/dpf89q/just_wrapped_up_quiet_for_react_native_this_lets/).
