### ISSUE TITLE
Podspec link is incorrect

### ISSUE THREAD

**Issue by patrickkeenan** [cawfree/react-native-quiet#3]
I believe the line in the readme should be:

The line pod 'react-native-quiet', :path => '**../node_modules/react-native-quiet**/react-native-quiet.podspec' is visible in your Podfile.

Rather than:

The line pod 'react-native-quiet', :path => '**../..**/react-native-quiet.podspec' is visible in your Podfile.

**Comment by cawfree** [comment]
Thanks a lot for the feedback @patrickkeenan! This is fixed now.
