### ISSUE TITLE
Android: Could not resolve project :quiet.

### ISSUE THREAD

**Issue by nabylb** [cawfree/react-native-quiet#5]
System:
    OS: macOS 10.15
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 264.83 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.2 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.10.3 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5

react-native-quiet version 0.0.2

Android build fails after autolink on RN 0.61.5. The node_modules/react-native-quiet/android/org.quietmodem.Quiet directory is empty.

<img width="839" alt="Screen Shot 2019-12-07 at 9 31 39 PM" src="https://user-images.githubusercontent.com/772506/70384765-4a622e00-1939-11ea-809b-510da39d2daa.png">

**Comment by cawfree** [comment]
Hey @nabylb, thanks for downloading. Sorry that this has happened.

We use `org.quietmodem.Quiet` as a git submodule dependency, and for whatever reason when installing via npm, this directory is not initialized. I'll look into it.

**Comment by cawfree** [comment]
Could you `yarn add react-native-quiet` and give it another go? :)

**Comment by nabylb** [comment]
Thanks @cawfree ! Android works now. This is a cool project. Let me know if you need help adding autolink or other features.

**Comment by cawfree** [comment]
Ah, that’s great news! Thanks a lot for raising the issue in the first
place.

That’s really kind of you! If you do find yourself adding anything to the
repository that you think might be useful for others, feel free to shoot me
a pull request.

Thanks again! 🙏
