### ISSUE TITLE
A problem occurred evaluating project ':quiet'.

### ISSUE THREAD

**Issue by thedevxen** [cawfree/react-native-quiet#6]
My React Version:
```json
"react": "16.9.0",
"react-native": "0.61.5",
```

I tried to link it manually. I followed [this](https://www.npmjs.com/package/react-native-quiet#android-1) way.

![image](https://user-images.githubusercontent.com/31907722/71308885-a8a60b00-2427-11ea-8d20-08c16d0804fc.png)

![image](https://user-images.githubusercontent.com/31907722/71308895-c1aebc00-2427-11ea-987c-8cbb53799d40.png)

**Comment by cawfree** [comment]
It doesn't look like your Android SDK directory is possibly not recognized
by your OS. Can you verify its existence in your `$PATH` variable?

**Comment by thedevxen** [comment]
It's not possible that I have not set the Android SDK in $PATH, as `react-naive run-android` works without any error on other projects..
![image](https://user-images.githubusercontent.com/31907722/71310527-21629280-243b-11ea-81f4-0b45ea907ae6.png)

**Comment by cawfree** [comment]
Ah okay, thanks for checking.

So, looking at this line in particular:

![image](https://imgur.com/kjasDXJ)

It is complaining that it can't find a `local.properties` file in your root `/android` project. Is that the case?

**Comment by thedevxen** [comment]
yes, that file doesn't exists

**Comment by cawfree** [comment]
Okay, try creating one with the following contents:

```env
android.useAndroidX=true
android.enableJetifier=true
```

Pretty surprised that this file isn't present in your project. It might be worth updating `react-native init` and re-running `react-native-init Quiet` and including this as a dependency in the new project, because I would imagine that this file would be included by default.

**Comment by thedevxen** [comment]
@cawfree i tried creating .a fresh project, but still getting the same error...
```
* What went wrong:
A problem occurred evaluating project ':quiet'.
> /Users/xen/Workspace/React-Native/Quiet/android/local.properties (No such file or directory)
```

**Comment by cawfree** [comment]
That's strange. :/ Have you tried creating the file manually?

**Comment by thedevxen** [comment]
I tried creating a new empty file, now the error has changed,
```
* What went wrong:
A problem occurred evaluating project ':quiet'.
> NDK location not found. Define location with ndk.dir in the local.properties file or with an ANDROID_NDK_ROOT environment variable.
```

**Comment by cawfree** [comment]
Okay, good. So you probably need to go ahead and configure the Android [ndk](https://developer.android.com/studio/projects/install-ndk).

You'll find this section of [Quiet for Android](https://github.com/quiet/org.quietmodem.Quiet#usage) useful.

I won't mark this issue as closed, but it does seem like you're running into external configuration factors that aren't directly related to `react-native-quiet`. :)

**Comment by thedevxen** [comment]
@cawfree after setting up the ndk, now i am getting this another error

```
* What went wrong:
Execution failed for task ':quiet:ndkBuild'.
> A problem occurred starting process 'command '/Users/xen/Library/Androi/ndk/ndk-build''
```

**Comment by Bisark** [comment]
@thedevxen probably you have to set up the path including the NDK version. 
Something like
`
ndk.dir=/home/bisark/Android/Sdk/ndk/20.1.5948944/
`

**Comment by JakinTayo** [comment]
![Alex](https://user-images.githubusercontent.com/46313179/78659641-c6f32200-78c3-11ea-95c0-3b2206bea904.PNG)

After following the docs I still have the Above issue.

**Comment by cawfree** [comment]
Hey all, since I closed the original issue it looks like I don't get visibility of any new comments.

@JakinTayo Have you confirmed `s_wallet/android/local.properties` exists?

By the way, Windows sometimes has issues with strange characters in filenames. What happens if you trying renaming your project to `swallet`?

Have you verified that you can run the example app?

**Comment by JakinTayo** [comment]
![image](https://user-images.githubusercontent.com/46313179/78664986-02461e80-78cd-11ea-8a87-4e4165ba9ed2.png)

**Comment by cawfree** [comment]
It looks like you haven't installed the Android ndk. Please [follow the ndk installation instructions carefully](https://github.com/quiet/org.quietmodem.Quiet#usage).

**Comment by JakinTayo** [comment]
So I Installed ndk and put the path in my local.properties file 

![image](https://user-images.githubusercontent.com/46313179/78685772-2106de00-78ea-11ea-81b0-892d330482d5.png)

**Comment by cawfree** [comment]
Does [this](https://stackoverflow.com/questions/29738953/ndkbuild-failure) help?

**Comment by JakinTayo** [comment]
No. I don't have this line in my build.gradle
![image](https://user-images.githubusercontent.com/46313179/78693077-a7bfb900-78f2-11ea-9127-1cdbbf0fa7a7.png)

**Comment by cawfree** [comment]
@JakinTayo Just looking a little closer at your screenshot, where are the file path separators? :S

![Screenshot 2020-04-08 at 02 13 36](https://user-images.githubusercontent.com/7922333/78733911-ba5fdf80-793e-11ea-9174-e8721afed8da.png)

**Comment by JakinTayo** [comment]
@cawfree I got it to work. But any time I try to npm install any package I get this error 
![image](https://user-images.githubusercontent.com/46313179/78781343-fbd0a900-7997-11ea-80ad-3967ce6c2429.png)

**Comment by cawfree** [comment]
Okay, that's great well done. It looks like you've installed two copies of React Native somewhere. (if you look close, your quiet node_modules has another node_modules inside.) This likely happened during your debugging. Just remove the nested directory and you should be set to go.

I'm going to close off this issue now, because these don't seem related to RNQuiet, but I will add further documentation to the README regarding the Android ndk because this seems to be tripping up quite a lot of people!

Thanks a lot!

**Comment by JakinTayo** [comment]
@ cawfree thanks a lot. I got it to work well. 
const blacklist = require('metro-config/src/defaults/blacklist');

module.exports = {
  resolver: {
        blacklistRE: blacklist([
            /node_modules\/.*\/node_modules\/react-native\/.*/,
        ])
    }

to my metro.config file

I checked the demo site and there is an option to transmit either via audible means or ultrasonic; is this also possible in the mobile version?

**Comment by JakinTayo** [comment]
![image](https://user-images.githubusercontent.com/46313179/79432763-2d62f900-7fc4-11ea-963b-a274a9d64a01.png)

My Bundler is running perfectly but the app is saying it can't invoke RNQuiet.start.
